[app]
ip_address = "0.0.0.0" # The listening IP address of the server
port = 4567 # The listening port of the server
max_threads = 30 # Number of concurrent threads to handle requests from Rocket.Chat and communicate with JIRA.

[message]
username = "JIRA" # Override username
use_real_names = true # Use peoples real names instead of jira usernames
icon_url = "https://confluence.atlassian.com/alldoc/files/169118009/169050326/4/1260504581635/jira_logo.png" # Override icon
date_pattern = "EEE, d MMM, yyyy" # Format dates according to https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
date_locale = "en-US" # Defines how things like week days and month names will be represented. Expects a IETF language tag
priority_colors = true # Color attachments according to issue priority
default_color = "#205081" # Fallback color when priority_colors is false or priority not recognized
fields = ["Assignee", "Status", "Reporter", "Priority", "Resolution", "Type", "Created", "Updated"] # Message fields to print
whitelisted_jira_key_prefixes = "([{<:" # Each character in the string is a valid prefix of a JIRA key. Allows for triggering in messages like "Jira key:ABC-123" and "(ABC-123)"
whitelisted_jira_key_suffixes = ")]}>!?" # Each character in the string is a valid suffix of a JIRA key. Allows for triggering in messages like "Look at ABC-123!" and "<ABC-123>"
max_text_length = 600 # The max length of the JIRA description until truncation happens

[rocketchat]
tokens = [] # Allowed Rocket.Chat tokens. An empty array means ALL tokens are allowed.
whitelisted_users = [] # Only messages from these users are considered. An empty array accepts messages from all users (unless blacklisted).
blacklisted_users = [] # No messages from these users will be considered.
whitelisted_channels = [] # Only messages from these channels are considered. An empty array accepts messages from all channels (unless blacklisted).
blacklisted_channels = [] # No messages from these channels will be considered.
ignore_bots = true # Whether to ignore all messages from bots
